export type BenefactorEdataFormState = {
  code: string
  name: string
  address: string
  city: string
  contactPerson: string
  phone: string
  email: string
  company: string
  fYear: string
  deleted: boolean
  userId: string
  scanId: string
  insertedOn: string
  insertedBy: string
  host: string
  versionBase64: string
  benefactorType: string
  country: string
  fax: string
  trn: string
  website: string
  legalName: string
  tradingName: string
  tin: string
  tradeLicenseNo: string
  tradeLicenseType: string
  tradeLicenseAuthority: string
  endpointId: string
  endpointScheme: string
  state: string
  postalCode: string
}

export type UpsertBenefactorEdataPayload = {
  uid?: number
  code: string
  name: string
  deleted: boolean
  address?: string
  city?: string
  contactPerson?: string
  phone?: string
  email?: string
  company?: number
  fYear?: number
  userId?: number
  scanId?: string
  insertedOn?: string
  insertedBy?: number
  host?: string
  versionBase64?: string
  benefactorType?: number
  country?: string
  fax?: string
  trn?: string
  website?: string
  legalName?: string
  tradingName?: string
  tin?: string
  tradeLicenseNo?: string
  tradeLicenseType?: string
  tradeLicenseAuthority?: string
  endpointId?: string
  endpointScheme?: string
  state?: string
  postalCode?: string
}

export const emptyBenefactorForm = (): BenefactorEdataFormState => ({
  code: '',
  name: '',
  address: '',
  city: '',
  contactPerson: '',
  phone: '',
  email: '',
  company: '',
  fYear: '',
  deleted: false,
  userId: '',
  scanId: '',
  insertedOn: '',
  insertedBy: '',
  host: '',
  versionBase64: '',
  benefactorType: '',
  country: '',
  fax: '',
  trn: '',
  website: '',
  legalName: '',
  tradingName: '',
  tin: '',
  tradeLicenseNo: '',
  tradeLicenseType: '',
  tradeLicenseAuthority: '',
  endpointId: '',
  endpointScheme: '',
  state: '',
  postalCode: '',
})
